### ISSUE TITLE
Responsive doesn't work

### ISSUE THREAD

**Issue by yerzinperez** [DataTables/Dist-DataTables-Responsive-Bootstrap5#1]
I am currently working with angular. I installed all the dependencies:

npm install --save datatables.net-bs5
npm install --save datatables.net-responsive-bs5

And added them to the angular.json:
JS
"node_modules/jquery/dist/jquery.min.js",
"node_modules/datatables.net/js/jquery.dataTables.js",
 "node_modules/datatables.net-bs5/js/dataTables.bootstrap5.js",
 "node_modules/datatables.net-responsive-bs5/js/responsive.bootstrap5.js"

CSS:

"node_modules/bootstrap/dist/css/bootstrap.min.css",
"node_modules/datatables.net-responsive-bs5/css/responsive.bootstrap5.css",
"node_modules/datatables.net-bs5/css/dataTables.bootstrap5.css"

But the browser console tells me:
![image](https://user-images.githubusercontent.com/46495310/206863320-e582538e-b77e-4d92-bf25-c938d13bec9b.png)
![image](https://user-images.githubusercontent.com/46495310/206863337-c173e3d3-30d4-4aa2-aa02-084c3a93caf4.png)

However, if I replace the content of the responsive.bootstrap5.js file with the script from the site mentioned below, it does work:

https://cdn.datatables.net/responsive/2.4.0/js/dataTables.responsive.js

**Comment by AllanJard** [comment]
Can you use StackBlitz to create a demonstration test case showing this issue please? I'm not well versed in Angular, but that probably shouldn't make any difference to this.

**Comment by yerzinperez** [comment]
Hi again,

I can't recreate the bug in stackblitz so I created a basic repository demonstrating the bug, I hope this helps.

https://github.com/yerzinperez/datatables-error-responsive

Thanks & regards.

**Comment by AllanJard** [comment]
Brilliant - thank you. Apologies, I've run out of time to look at this today - will do so tomorrow.

**Comment by AllanJard** [comment]
I've just sent a pull request with a fix for this.

Also, you'll probably want to add `style="width: 100%"` to your `<table>` tag to make sure it takes up the width available.
